---
- name: "Gather operating system variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution_file_variety | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags: ca

- name: "Copy certificates"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ca_path }}/"
    mode: "0644"
  with_fileglob:
    - "{{ ca_source_path }}"
  register: __ca_copy
  notify: Update truststore
  tags: ca

- name: "Update truststore"
  ansible.builtin.command:
    cmd: "{{ ca_update }}"
  when: __ca_copy.changed
  tags: ca
