---
- name: "Copy script for /etc/profile.d"
  ansible.builtin.copy:
    src: "{{ item.source }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - source: "../files/bashrc/git-prompt.sh"
      dest: "/etc/profile.d/git-prompt.sh"
      mode: "0755"
    - source: "../files/bashrc/ssh-agent.sh"
      dest: "/etc/profile.d/ssh-agent.sh"
      mode: "0755"
  tags: prompt

- name: "Copy files"
  ansible.builtin.copy:
    src: "{{ item.source }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  notify: "Update font cache"
  with_items:
    - source: "../files/prompt/yq-v{{ prompt_yq_version }}-{{ ansible_system | lower }}-{{ ansible_architecture }}"
      dest: "/usr/local/bin/yq"
      mode: "0755"
    - source: "../files/prompt/bcrypt"
      dest: "/usr/local/bin/bycrypt"
      mode: "0755"
    - source: ../files/bashrc/ms.sh
      dest: "/root/.ms.sh"
      mode: "0755"
    - source: ../files/bashrc/tmux.conf
      dest: "/root/.tmux.conf"
      mode: "0644"
    - source: ../files/bashrc/vimrc
      dest: "/root/.vimrc"
      mode: "0644"
    - source: ../files/bashrc/gitconfig
      dest: "/root/.gitconfig"
      mode: "0644"
  tags: prompt
