---
sshd_bind_ips: false

defaults_sshd_client:
  ForwardX11Trusted: true
  GSSAPIAuthentication: true
  SendEnv:
    - LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
    - LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT
    - LC_IDENTIFICATION LC_ALL LANGUAGE
    - XMODIFIERS

defaults_sshd_server:
  AcceptEnv:
    - LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
    - LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT
    - LC_IDENTIFICATION LC_ALL LANGUAGE
    - XMODIFIERS
  AddressFamily: any
  ChallengeResponseAuthentication: false
  GSSAPIAuthentication: true
  GSSAPICleanupCredentials: false
  HostKey:
    - /etc/ssh/ssh_host_rsa_key
  PasswordAuthentication: "no"
  PermitRootLogin: "no"
  PermitEmptyPasswords: "no"
  Port: 22
  Protocol: 2
  LoginGraceTime: 30
  StrictModes: "yes"
  MaxStartups: 200
  Subsystem: 'sftp internal-sftp'
  SyslogFacility: AUTHPRIV
  UsePAM: true
  X11Forwarding: true
  PrintMotd: "yes"
  PrintLastLog: "yes"
  Ciphers: aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
  MACs: hmac-sha2-256,hmac-sha2-512
  KexAlgorithms: curve25519-sha256,diffie-hellman-group-exchange-sha256
  PermitUserEnvironment: "no"
  MaxSessions: 10
  TCPKeepAlive: "yes"
  ClientAliveInterval: 300
  ClientAliveCountMax: 2
