- name: "Remove other mtas"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - exim4
    - sendmail
    - ssmtp
    - msmtp
  tags:
    - postfix-mta

- name: "Install postfix"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - postfix
    - mailutils
    - libsasl2-modules
    - ca-certificates
  tags:
    - postfix-mta

- name: "Configure /etc/postfix/main.cf"
  ansible.builtin.template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: "0644"
    validate: "/usr/sbin/postfix check"
  notify: "Restart postfix"
  tags:
    - postfix-mta

- name: "Confiugure /etc/postfix/header_check"
  ansible.builtin.template:
    src: header_check.j2
    dest: /etc/postfix/header_check
    owner: root
    group: root
    mode: "0644"
  notify: "Restart postfix"
  tags:
    - postfix-mta

- name: "Configure /etc/postfix/sender_canonical"
  ansible.builtin.template:
    src: sender_canonical.j2
    dest: /etc/postfix/sender_canonical
    owner: root
    group: root
    mode: "0644"
  notify: "Restart postfix"
  tags:
    - postfix-mta

- name: "Configure aliases"
  ansible.builtin.template:
    src: aliases.j2
    dest: /etc/aliases
    owner: root
    group: root
    mode: "0644"
  notify: "Update aliases"
  tags:
    - postfix-mta

- name: "Configure /etc/mail.rc"
  ansible.builtin.template:
    src: mail.rc.j2
    dest: /etc/mail.rc
    owner: root
    group: root
    mode: "0644"
  notify: "Update aliases"
  tags:
    - postfix-mta
